// 1. CRIE UMA FUNÇÃO QUE SOME 2 NÚMEROS
// 2. CRIE UMA FUNÇÃO QUE SUBTRAIA 2 NÚMEROS
// 3. CRIE UMA FUNÇÃO QUE MULTIPLIQUE 2 NÚMEROS
// 4. CRIE UMA FUNÇÃO QUE DIVIDA 2 NÚMEROS

// 5. INVOQUE CADA UMA DESSAS FUNÇÕES, 
    // SALVANDO OS SEUS RETORNOS EM VARIÁVEIS

// 6. CALCULE O RESULTADO DA SOMA ENTRE TODOS OS RETORNOS 
    // OBTIDOS
    
// 7. MOSTRE TUDO ATRAVÉS DO CONSOLE DO NAVEGADOR